name: youtube_plyr_iframe
description: Flutter port of the official YouTube iFrame player API. Supports web & mobile platforms.
version: 1.3.0+1
repository: https://github.com/jonatadashi/youtube_player_iframe
homepage: https://github.com/jonatadashi/youtube_player_iframe

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.22.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: '>=4.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter