name: youtube_plyr_iframe
description: Fork of Youtube Player Iframe. Supports web & mobile platforms.

version: 2.0.1

repository: https://github.com/jonatadashi/youtube_plyr_iframe
homepage: https://github.com/jonatadashi/youtube_plyr_iframe

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: '>=4.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter